
export const iconNames = [
  "Activity", "Airplay", "AlarmCheck", "AlarmClockOff", "AlarmClock", "AlarmMinus", "AlarmPlus",
  "Album", "AlertCircle", "AlertOctagon", "AlertTriangle", "AlignCenter", "AlignJustify",
  "AlignLeft", "AlignRight", "Anchor", "Aperture", "Archive", "ArrowDownCircle", "ArrowDownLeft",
  "ArrowDownRight", "ArrowDown", "ArrowLeftCircle", "ArrowLeft", "ArrowRightCircle", "ArrowRight",
  "ArrowUpCircle", "ArrowUpLeft", "ArrowUpRight", "ArrowUp", "AtSign", "Award", "Axe", "Banknote", "BarChart2",
  "BarChart", "Baseline", "Bath", "BatteryCharging", "BatteryFull", "BatteryLow", "BatteryMedium",
  "Battery", "Beaker", "BellMinus", "BellOff", "BellPlus", "Bell", "Bike", "Binary", "Bitcoin",
  "Bold", "Bomb", "BookOpen", "Book", "Bookmark", "Bot", "Box", "BoxSelect", "Briefcase", "Brush", "Bug", "Building2",
  "Building", "Bus", "Calculator", "Calendar", "CameraOff", "Camera", "Car", "CaseLower", "CaseSensitive",
  "CaseUpper", "Cast", "CheckCircle2", "CheckCircle", "CheckSquare", "Check", "ChevronDown",
  "ChevronLeft", "ChevronRight", "ChevronUp", "ChevronsDown", "ChevronsLeft", "ChevronsRight",
  "ChevronsUp", "Chrome", "Church", "Circle", "Clipboard", "Clock", "CloudDrizzle", "CloudLightning",
  "CloudOff", "CloudRain", "CloudSnow", "Cloud", "Code", "Codepen", "Codesandbox", "Coffee", "Columns",
  "Command", "Compass", "Contact", "Copy", "Copyleft", "Copyright", "CornerDownLeft", "CornerDownRight",
 "CornerLeftDown", "CornerLeftUp", "CornerRightDown", "CornerRightUp", "CornerUpLeft", "CornerUpRight",
  "Cpu", "CreditCard", "Crop", "Crosshair", "Crown", "CupSoda", "Currency", "Database", "Delete",
  "Disc", "DivideCircle", "DivideSquare", "Divide", "DollarSign", "DownloadCloud", "Download",
  "Dribbble", "Droplet", "Edit2", "Edit3", "Edit", "Egg", "Eraser", "Euro", "ExternalLink", "EyeOff",
  "Eye", "Facebook", "FastForward", "Feather", "Figma", "FileCheck2", "FileCheck", "FileCode",
  "FileDigit", "FileDown", "FileEdit", "FileMinus2", "FileMinus", "FilePlus2", "FilePlus", "FileSearch",
  "FileText", "FileUp", "FileX2", "FileX", "File", "Film", "Filter", "Flag", "Flame", "FlaskConical", "FlaskRound",
  "Folder", "Folders", "FormInput", "Forward", "Framer", "Frown", "FunctionSquare", "Gamepad2", "Gamepad",
  "Gauge", "Gavel", "Gem", "GitBranch", "GitCommit", "GitMerge", "GitPullRequest", "Github", "Gitlab",
  "Globe2", "Globe", "Grab", "GraduationCap", "Grid", "Hammer", "Hand", "HardDrive", "HardHat", "Hash",
  "Headphones", "Heart", "HelpCircle", "Hexagon", "Home", "Image", "Inbox", "Indent", "Info",
  "Instagram", "Italic", "IterationCcw", "IterationCw", "Joystick", "Key", "Keyboard", "Landmark",
  "Languages", "Laptop2", "Laptop", "Layers", "LayoutDashboard", "LayoutGrid", "LayoutList",
  "LayoutTemplate", "Layout", "Library", "LifeBuoy", "LightbulbOff", "Lightbulb", "Link2", "Link",
  "Linkedin", "List", "Loader2", "Loader", "Lock", "LogIn", "LogOut", "Mail", "MapPin", "Map",
  "Maximize2", "Maximize", "Meh", "Menu", "MessageCircle", "MessageSquare", "MicOff", "Mic",
  "Minimize2", "Minimize", "MinusCircle", "MinusSquare", "Minus", "Monitor", "Moon", "MoreHorizontal",
  "MoreVertical", "MousePointer", "Move", "Music", "Navigation2", "Navigation", "Octagon",
  "Option", "Outdent", "Package", "Paintbrush2", "Paintbrush", "Palette", "Paperclip", "ParkingCircle",
  "ParkingSquare", "PartyPopper", "PauseCircle", "Pause", "PenTool", "Percent", "PersonStanding",
  "PhoneCall", "PhoneForwarded", "PhoneIncoming", "PhoneMissed", "PhoneOff", "PhoneOutgoing",
  "Phone", "PieChart", "Pilcrow", "Pin", "PlayCircle", "Play", "PlugZap", "PlusCircle", "PlusSquare",
  "Plus", "Pocket", "Podcast", "Pointer", "PoundSterling", "PowerOff", "Power", "Printer",
  "QrCode", "Quote", "RadioReceiver", "Radio", "Redo", "RefreshCcw", "RefreshCw", "Regex",
  "Repeat1", "Repeat", "ReplyAll", "Reply", "Rewind", "Rocket", "RockingChair", "RotateCcw",
  "RotateCw", "Rss", "Ruler", "Save", "Scale", "ScanLine", "Scan", "Scissors", "ScreenShareOff",
  "ScreenShare", "Search", "Send", "SeparatorHorizontal", "SeparatorVertical", "Server",
  "Settings2", "Settings", "Share2", "Share", "Sheet", "ShieldAlert", "ShieldCheck", "ShieldClose",
  "ShieldOff", "Shield", "ShoppingBag", "ShoppingCart", "Shovel", "SidebarClose", "SidebarOpen",
  "Sidebar", "Sigma", "SignalHigh", "SignalLow", "SignalMedium", "SignalZero", "Signal", "SkipBack",
  "SkipForward", "Skull", "Slack", "Slash", "Slice", "Sliders", "Smartphone", "Smile", "Snowflake",
  "SortAsc", "SortDesc", "Speaker", "Sprout", "Square", "Star", "Sticker", "StopCircle", "Strikethrough",
  "Subscript", "Sun", "Sunrise", "Sunset", "Superscript", "SwissFranc", "SwitchCamera", "Table",
  "Tablet", "Tag", "Tags", "Target", "Tent", "TerminalSquare", "Terminal", "TextCursorInput",
  "TextCursor", "TextSelect", "ThumbsDown", "ThumbsUp", "Ticket", "TimerOff", "TimerReset", "Timer",
  "ToggleLeft", "ToggleRight", "Tornado", "Train", "Trash2", "Trash", "Trello", "TrendingDown",
  "TrendingUp", "Triangle", "Truck", "Tv2", "Tv", "Twitch", "Twitter", "Type", "Umbrella",
  "Underline", "Undo", "Unlink2", "Unlink", "Unlock", "UploadCloud", "Upload", "UserCheck",
  "UserMinus", "UserPlus", "UserX", "User", "Users", "Verified", "Vibrate", "VideoOff", "Video",
  "Voicemail", "Volume1", "Volume2", "VolumeX", "Volume", "Wallet", "Watch", "Webhook", "WifiOff",
  "Wifi", "Wind", "Wrench", "XCircle", "XOctagon", "XSquare", "X", "Youtube", "ZapOff", "Zap",
  "ZoomIn", "ZoomOut"
];
